# Generated by Django 3.0.3 on 2020-03-28 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='tour_product',
        ),
        migrations.AddField(
            model_name='review',
            name='tour_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.TourProduct'),
        ),
        migrations.DeleteModel(
            name='ReviewTourProduct',
        ),
    ]
